<?php

/**
 * @file
 * Contains external links popup hooks implementation.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function extlink_popup_form_extlink_admin_settings_alter(&$form, FormStateInterface $form_state) {
  \Drupal::service('extlink_popup.popup_service')->extlinkSettingsFormAlter($form, $form_state);
}

/**
 * Implements hook_page_attachments().
 */
function extlink_popup_page_attachments(array &$attachments) {
  \Drupal::service('extlink_popup.popup_service')->providePageAttachments($attachments);
}
